### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by priyavatsya** [ImanMohi/RTU-DigitalLibrary#224]
#Sum of natural numbers up to num

num = 16

if num < 0:
   print("Enter a positive number")
else:
   sum = 0
   # use while loop to iterate until zero
   while(num > 0):
       sum += num
       num -= 1
   print("The sum is", sum)

**Comment by onkcharkupalli1051** [comment]
accumulate sum to 0 before the while loop!

**Comment by kaushalendra-pandey** [comment]
Use the general AP formula to make it a O(1) code.

`def sum_num(n):
    return (n * (n+1)) // 2`
